# Generated by Django 5.1.4 on 2025-03-06 21:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='year_ended',
            field=models.PositiveIntegerField(blank=True, help_text='Ended year in format YYYY.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2099)]),
        ),
        migrations.AddField(
            model_name='character',
            name='year_started',
            field=models.PositiveIntegerField(blank=True, help_text='Started year in format YYYY.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2099)]),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('user', 'nickname', 'game')},
        ),
    ]
