# Generated by Django 5.2.9 on 2025-12-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='customuser',
            name='github_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS_ONLY', 'Friends Only'), ('PRIVATE', 'Private')], default='FRIENDS_ONLY', help_text='Who can see your profile', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stackoverflow_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='steam_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='youtube_channel',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='identity_revealed',
            field=models.BooleanField(default=False, help_text='Whether sender revealed their user identity'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='privacy_mode',
            field=models.CharField(choices=[('ANONYMOUS', 'Anonymous'), ('REVEAL_IDENTITY', 'Reveal Identity')], default='ANONYMOUS', help_text='Privacy mode when message was sent', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CharacterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_bio', models.TextField(blank=True, max_length=2000)),
                ('custom_images', models.JSONField(blank=True, default=list)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('memories', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=True, help_text='Show profile to everyone')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.character')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_character1', to='app.character')),
                ('character2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_as_character2', to='app.character')),
            ],
            options={
                'indexes': [models.Index(fields=['character1', 'character2'], name='app_charact_charact_f2af1c_idx')],
                'unique_together': {('character1', 'character2')},
            },
        ),
        migrations.CreateModel(
            name='CharacterFriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('receiver_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to='app.character')),
                ('sender_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to='app.character')),
            ],
            options={
                'unique_together': {('sender_character', 'receiver_character')},
            },
        ),
    ]
