# Generated by Django 5.1.4 on 2025-01-01 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='games',
        ),
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='character',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.game'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
    ]
