# Generated by Django 5.2.9 on 2025-12-28 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_custom_links_customuser_github_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(help_text='POKE content (max 100 characters, no URLs or links)', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESPONDED', 'Responded'), ('IGNORED', 'Ignored'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=20)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reported_as_spam', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('receiver_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_pokes', to='app.character')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_pokes', to=settings.AUTH_USER_MODEL)),
                ('sender_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_pokes', to='app.character')),
            ],
            options={
                'ordering': ['-sent_date'],
                'indexes': [models.Index(fields=['receiver_character', 'status', '-sent_date'], name='app_poke_receive_242c88_idx'), models.Index(fields=['sender_character', 'status'], name='app_poke_sender__9a8a49_idx')],
                'unique_together': {('sender_character', 'receiver_character')},
            },
        ),
        migrations.CreateModel(
            name='PokeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking', max_length=200)),
                ('blocked_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_poke_receivers', to='app.character')),
                ('blocker_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_poke_senders', to='app.character')),
            ],
            options={
                'indexes': [models.Index(fields=['blocker_character', 'blocked_character'], name='app_pokeblo_blocker_b73628_idx')],
                'unique_together': {('blocker_character', 'blocked_character')},
            },
        ),
    ]
