# Generated by Django 5.1.4 on 2025-03-06 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_character_year_ended_character_year_started_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePlayed',
        ),
    ]
