# Generated by Django 5.2.9 on 2025-12-28 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_poke_pokeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterIdentityReveal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revealed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the identity reveal is currently active')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the identity reveal was revoked', null=True)),
                ('revealed_to_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_reveals_received', to='app.character')),
                ('revealing_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_reveals_sent', to='app.character')),
            ],
            options={
                'ordering': ['-revealed_at'],
                'unique_together': {('revealing_character', 'revealed_to_character')},
            },
        ),
    ]
