# Generated by Django 5.1.4 on 2025-03-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_gameplayed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='visibility',
        ),
    ]
