# Generated by Django 5.2.9 on 2025-12-28 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_characteridentityreveal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, help_text='Optional reason for blocking (not shown to blocked user)', max_length=500)),
                ('reported_as_spam', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_characters', to='app.character')),
                ('blocker_character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_characters', to='app.character')),
            ],
            options={
                'ordering': ['-blocked_at'],
                'indexes': [models.Index(fields=['blocker_character', 'blocked_at'], name='app_charact_blocker_1cae22_idx'), models.Index(fields=['blocked_character'], name='app_charact_blocked_363613_idx')],
                'unique_together': {('blocker_character', 'blocked_character')},
            },
        ),
    ]
