# Generated by Django 5.1.4 on 2025-03-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_character_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='app.character'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('USER', 'User message'), ('CHARACTER', 'Character message')], default='USER', max_length=10),
        ),
    ]
