# Generated by Django 5.1.4 on 2025-03-06 22:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_character_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
